In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
iris = datasets.load_iris()
from scipy.optimize import fmin_tnc

In [2]:
df = pd.read_csv('qwert.txt', header=None)

In [3]:
df.head()

0          1  2
0  34.623660  78.024693  0
1  30.286711  43.894998  0
2  35.847409  72.902198  0
3  60.182599  86.308552  1
4  79.032736  75.344376  1

In [4]:
X7 = df.iloc[:,:-1]
Y7 = df.iloc[:,-1]
#t1 = df.loc[Y7 == 1]
#t2 = df.loc[Y7 == 0]

In [5]:
X7 = np.c_[np.ones((X7.shape[0], 1)), X7]
Y7 = Y7[:, np.newaxis]
theta = np.zeros((X7.shape[1], 1))

** Starts here

In [2]:
data = pd.DataFrame(iris['data'])
target = pd.DataFrame(iris['target'])
dt = pd.concat([data, target], axis =1)
dt.columns = ['sl', 'sw', 'pl', 'pw', 'type']
dt = dt.loc[dt['type'] != 2]

X = dt.drop('type', axis = 1)
Y = dt['type']

#theta = np.zeros((X.shape[1], 1))
X = np.c_[np.ones((X.shape[0], 1)), X]
Y = Y[:, np.newaxis]
theta = np.zeros((X.shape[1], 1))

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def net_input(theta, x):
    return np.dot(x, theta)

def probability(theta, x):
    return sigmoid(net_input(theta,x))

def cost_function(theta, x, y):
    m = x.shape[0]
    total_cost = -(1 / m) * np.sum(y * np.log(probability(theta, x)) + (1 - y) * np.log(1 - probability(theta, x)))
    return total_cost

def gradient(theta, x, y):
    m = x.shape[0]
    return (1 / m) * np.dot(x.T, sigmoid(net_input(theta, x)) - y)

#def nesterov_momentum():
    
    
    

def fit_func(x, y, theta):
    opt_weights = fmin_tnc(func=cost_function, x0=theta, fprime=gradient, args=(x, y.flatten()))
    return opt_weights[0]

def predict(x, parameters):
    theta = parameters[:, np.newaxis]
    return probability(theta, x)

def accuracy(x, actual_classes, parameters, probab_threshold=0.5):
    predicted_classes = (predict(x, parameters) >= probab_threshold).astype(int)
    predicted_classes = predicted_classes.flatten()
    accuracy = np.mean(predicted_classes == actual_classes)
    return accuracy * 100, predicted_classes


** SGD

In [4]:
parameters1 = fit_func(X, Y, theta)

C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in log
  if sys.path[0] == '':
C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in multiply
  if sys.path[0] == '':


In [5]:
parameters1

array([-1.38271367, -2.35978503, -7.25544159, 11.92283583,  5.766718  ])

In [6]:
accur1, pred_classes1 = accuracy(X, Y.flatten(), parameters1)

In [8]:
pred_classes1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
Y.flatten()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
grad - градиент,  lr - скорость обучения,  g -  накопленный градиент (иннициализируем нулем),
gamma -  коеффициент релаксации (управляет скоростью затухания градиента) обычно 0.9
обновляем веса:
g = gamma * g + (1 - gamma) * grad
w_i_ = w_i-1_ - lr * g (edited) 

*******************************************

In [15]:
def predict(row, coefficients):
    yhat = coefficients[0]
    for i in range(len(row)-1):
        yhat += coefficients[i + 1] * row[i]
    return 1.0 / (1.0 + np.exp(-yhat))

def coefficients_sgd(train, l_rate, n_epoch):
    coef = [0.0 for i in range(len(train[0]))]
    for epoch in range(n_epoch):
        sum_error = 0
        for row in train:
            yhat = predict(row, coef)
            error = row[-1] - yhat
            sum_error += error**2
            coef[0] = coef[0] + l_rate * error * yhat * (1.0 - yhat)
            for i in range(len(row)-1):
                coef[i + 1] = coef[i + 1] + l_rate * error * yhat * (1.0 - yhat) * row[i]
    print('>epoch=%d, lrate=%.3f, error=%.3f' % (epoch, l_rate, sum_error))
    return coef

g = gamma * g + (1 - gamma) * grad
w_i_ = w_i-1_ - lr * g (edited) 


def coefficients_nesterov(train, l_rate, n_epoch, gamma=0.9, g=0):
    coef = [0.0 for i in range(len(train[0]))]
    for epoch in range(n_epoch):
        sum_error = 0
        for row in train:
            yhat = predict(row, coef)
            error = row[-1] - yhat
            sum_error += error**2
            coef[0] = coef[0] + l_rate * error * yhat * (1.0 - yhat)
            for i in range(len(row)-1):
                coef[i + 1] = coef[i + 1] + l_rate * error * yhat * (1.0 - yhat) * row[i]
    print('>epoch=%d, lrate=%.3f, error=%.3f' % (epoch, l_rate, sum_error))
    return coef


# test predictions
dataset = [[2.7810836,2.550537003,0],
    [1.465489372,2.362125076,0],
    [3.396561688,4.400293529,0],
    [1.38807019,1.850220317,0],
    [3.06407232,3.005305973,0],
    [7.627531214,2.759262235,1],
    [5.332441248,2.088626775,1],
    [6.922596716,1.77106367,1],
    [8.675418651,-0.242068655,1],
    [7.673756466,3.508563011,1]]

l_rate = 0.1
n_epoch = 1000
coef = coefficients_sgd(dataset, l_rate, n_epoch)
print(coef)

>epoch=999, lrate=0.100, error=0.007
[-1.0740409360055667, 1.8779376220283672, -2.761565330016219]


In [ ]:
>epoch=999, lrate=0.100, error=0.007
[-1.0740409360055667, 1.8779376220283672, -2.761565330016219]